# -*- coding: utf-8 -*-
"""Aviation thing

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1PPDPs-tkse1fRJQKS-hciTxikgrWrHaa
"""

from sklearn import datasets
!pip install pandas
from sklearn import datasets
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

from google.colab import drive
drive.mount("/content/drive/")

url="/content/drive/MyDrive/aircrashesFullDataUpdated_2024.csv"
plane_df=pd.read_csv(url)
plane_df.head()

# @title Fatalities (air) vs Aboard

from matplotlib import pyplot as plt
plane_df.plot(kind='scatter', x='Fatalities (air)', y='Aboard', s=32, alpha=.8)
plt.gca().spines[['top', 'right',]].set_visible(False)

len(plane_df["Year"].value_counts())
plane_df["Year"].value_counts
plt.plot(len(plane_df["Year"].value_counts()),y=plane_df["Year"].value_counts)





